FROM centos:centos7

# 设置固定的项目路径
ENV WORKDIR /root
ENV TZ=Asia/Shanghai

RUN yum update -y   && export DISPLAY=:0.0 &&\
    yum install -y deltarpm  wget  libreoffice  libreoffice-headless  libreoffice-writer ImageMagick  openssl  xorg-x11-fonts-75dpi && \
    localedef -i en_US -f UTF-8 en_US.UTF-8  && yum clean all

CMD  ["/bin/bash"]

# ------------------------------------本地打包镜像---------------------
# docker build -t  goviewfile:v0.7  .
# docker run -d  -p 8082:8082 镜像ID
